blueprints/profile/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask import current_app as app
from flask_login import *
from blueprints.models import *
from sqlescapy import sqlescape
from ..forms import update_profileForm

# Blueprint Configuration
profile_bp = Blueprint(
    'profile_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

#Route per visualizzare il proprio profilo

#A questa pagina ha accesso chiunque
#Questa route reindirizza alla propria pagina profilo, in cui oltre alla foto profilo (icona)
#e al proprio nome, vi sono 3 bottoni: Logout, per eseguire il logout, Modifica profilo, per cambiare il proprio nome
#e/o il tipo di account, Cancella profilo, per eliminare l'utente dal DB

@profile_bp.route('/profile')
@login_required # richiede autenticazione
def profile():
    if(current_user.Profile == 'Artist'):
        session = Session(bind=engine["artist"])
    elif(current_user.Profile == 'Premium'):
        session = Session(bind=engine["premium"])
    else:
        session = Session(bind=engine["free"])

    playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
        
    return render_template("profile.html", user = current_user, playlists=playlists)

#Route per aggiornare il proprio profilo

#A questa pagina ha accesso chiunque
#Una volta caricate le informazioni necessarie ala modifica della profilo, prese dall'apposito form,
#se tutte le informazioni sono ammesse, viene modificato il profilo
#Se le informazioni non sono ammesse, e questo avviene quando 1)il nome utente eccede i 20 ch (gestito dal form)
#                                                            
#si resterà sulla pagina dedicata al form, che mostrerà specifici messaggi d'errore


@profile_bp.route('/update_info', methods=['GET', 'POST']) 
@login_required
def update_info():
    if(current_user.Profile == 'Artist'):
        session = Session(bind=engine["artist"])
    elif(current_user.Profile == 'Premium'):
        session = Session(bind=engine["premium"])
    else:
        session = Session(bind=engine["free"])

    form = update_profileForm(name=current_user.Name, profile=current_user.Profile)

    playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
        
    if form.validate_on_submit():
        name = sqlescape(form.name.data)
        prf = form.profile.data
        
        user = session.query(Users).filter(Users.Email == current_user.Email).first()
        Users.update_user(user, name, session)
        Users.update_profile(user, prf, session)
                
        return redirect(url_for('profile_bp.profile'))
        
    return render_template("update_info.html", form=form, playlists=playlists, user=current_user)


#Route per cancellare l'utente dal DB

#A questa funzionalità ha accesso chiunque
#Una volta eseguito il logout, l'utente viene rimosso dal DB, portando alla cancellazione di ogni suo contenuto (playlist, canzoni, album, 'Mi piace')

@profile_bp.route('/delete_profile')
@login_required
def delete_profile():
    if(current_user.Profile == 'Artist'):
        session = Session(bind=engine["artist"])
    elif(current_user.Profile == 'Premium'):
        session = Session(bind=engine["premium"])
    else:
        session = Session(bind=engine["free"])

    user = session.query(Users).filter(Users.Email == current_user.Email).first()
    songs_liked=session.query(Songs).filter(Songs.Id.in_(session.query(Users_liked_Songs.song_id).filter(Users_liked_Songs.user_email==user.Email))).all()
    albums_liked=session.query(Albums).filter(Albums.Id.in_(session.query(Users_liked_Albums.album_id).filter(Users_liked_Albums.user_email==user.Email))).all()
    
    for s in songs_liked:
        Songs.update_likes(s.N_Likes - 1, s.Id, session)

    for a in albums_liked:
        Albums.update_likes(a.N_Likes - 1, a.Id, session)
    
    logout_user()
    Users.delete_user(user, session)
    
    return redirect(url_for("login_bp.login"))

blueprints/profile/templates/profile.html
{% extends 'layout.html' %}

{% block content %}
<style>
    .logout_btn {
        background-color:#d71e31; 
        border:none; 
        border-radius:10vw;
        color: rgb(249, 248, 241);
        padding: 0.8vw 1.2vw;
      }
    .logout_btn:hover {
        background-color: #610202;
      }
</style>
<table style="width:100%;">
    <tr>
        <td style="padding-left:1%;"> <h1>Il tuo profilo </h1> </td>
        <td style="text-align:right; padding-right:2%;"> 
            <form action="/logout">
                <button type="submit"> LOGOUT </button> 
            </form>
        </td>
    </tr>
</table>

<div id="myPopup" style= "display: none; text-align: center;  background-color: #1d1d1d; border-radius: 5vw;">
    Vuoi davvero cancellare il tuo profilo? <br>
    <a class="logout_btn" href="#" onclick="myFunction()" style="text-align: center; padding: 0 0.8vw;">No</a>
    <a class="submit_btn" href="{{ url_for('profile_bp.delete_profile') }}" style="text-align: center; padding: 0 1.2vw;">Sì</a>
</div>

<div style="display:inline-block; width:30%;">
    <img src="..\static\img\profile.png" style="width:100%;">
</div>

<div style="display:inline-block; width:35%;">
    <h1 id="user_name">{{user.Name}}</h1> 
    <a href="{{ url_for('profile_bp.update_info') }}">
        <button id="button">Modifica profilo</button>
    </a>
    <br>
    <a href="#">
        <button class="logout_btn" style="transform: translateY(+25%)" onclick="myFunction()">Cancella profilo</button>
    </a>

    <script>
        // When the user clicks on <div>, open the popup
        function myFunction() {
          var popup = document.getElementById("myPopup");
          if (popup.style.display=="none")
                popup.style.display="block"
          else
                popup.style.display="none"
        }
    </script>
</div>    

{% endblock %}

blueprints/profile/templates/update_info.html
{% extends 'layout.html' %}

{% block content %}
    <div class="w3-container"> <h1>Il tuo profilo </h1> </div>

{% with errors = get_flashed_messages(category_filter=["error"]) %}
  {% if errors %}
    <div id="myErrors" class="alert-message block-message error" style="text-align: center; background-color: #1d1d1d; border-radius: 5vw;">
          <ul>
              {%- for msg in errors %}
                <li style="text-align: center;">{{ msg }}</li>
              {% endfor -%}
          </ul>
          <a id="closeButton" class="submit_btn" href="#" onclick="myFunction()" style="text-align: center; padding: 0 0.8vw;">Ok</a>
    </div>
  {% endif %}
{% endwith %}

<script>
  function myFunction() {
    var x = document.getElementById("myErrors");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>

<h2 class="title" style="text-align:center;">Aggiorna il tuo profilo</h2>

<form method="POST" action="{{ url_for('profile_bp.update_info') }}">
  {{ form.csrf_token }}

  <fieldset class="form-field">
    {{ form.name.label }} 
    {{ form.name }}
    {% if form.name.errors %}
      <ul class="errors">
        {% for error in form.name.errors %}
          <li class="error">
            <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  </fieldset>
  <br>
  <fieldset class="form-field">
    {{ form.profile.label }} 
    {{ form.profile }}
    {% if form.profile.errors %}
      <ul class="errors">
        {% for error in form.profile.errors %}
          <li class="error">
            <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  </fieldset>

  <br>
  {{ form.submit(class_="submit_btn") }}
</form>


{% endblock %}