blueprints/lib/routes.py
from flask import Blueprint, render_template
from flask import current_app as app
from flask_login import *
from blueprints.models import *

# Blueprint Configuration
library_bp = Blueprint(
    'library_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


#Route per visualizzare le playlist nella libreria

#A questa pagina ha accesso chiunque
#Semplicemente vengono collezionate le playlist dell'utente, utili anche a layout.html
#Oltre all'icona e al nome verranno visualizzati un bottone per eliminare e uno per modificare la playlist
#In cima alla pagina dei bottoni permettono di scorrere la libreria e passare ad altri contenuti
#Cliccando sull'icona o sul nome della playlist si viene indirizzati alla pagina della medesima
#dove se ne possono vedere il nome, la durata, quanti e quali brani vi sono, ed eventualmente toglierne/aggiungerne

@library_bp.route('/library')
@login_required
def library():
    if(current_user.Profile == 'Artist'):
        session = Session(bind=engine["artist"])
    elif(current_user.Profile == 'Premium'):
        session = Session(bind=engine["premium"])
    else:
        session = Session(bind=engine["free"])

    playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
    return render_template("library.html", playlists=playlists, user=current_user)

 
#Route per visualizzare gli album a cui l'utente ha messo 'Mi piace' nella libreria

#A questa pagina ha accesso chiunque
#Semplicemente vengono collezionati gli album a cui l'utente ha messo 'Mi piace' e in una lista
#vengono inserite n-uple contenenti le informazioni da visualizzare come il nome, la durata, la casa discografica, ecc..
#Cliccando sull'icona o sul nome si viene reindirizzati alla pagina dell'album
#Cliccando sul nome dell'artista si viene reindirizzati alla pagina dell'artista
#In cima alla pagina dei bottoni permettono di scorrere la libreria e passare ad altri contenuti
   
@library_bp.route('/albums')
@login_required
def albums():
    if(current_user.Profile == 'Artist'):
        session = Session(bind=engine["artist"])
    elif(current_user.Profile == 'Premium'):
        session = Session(bind=engine["premium"])
    else:
        session = Session(bind=engine["free"])

    playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
    albums = session.query(Albums).filter(Albums.Id.in_(session.query(Users_liked_Albums.album_id).filter(Users_liked_Albums.user_email==current_user.Email))) 
    
    lst_a=[]
    for a in albums:
        artist = session.query(Users).filter(Users.Email == a.Artist).first()
        lst_a.append([a.Name, artist.Name, a.Record_House, a.ReleaseDate, a.Duration, a.Id, artist.Email])
    return render_template("albums.html", playlists=playlists, user=current_user, albums=lst_a)


#Route per visualizzare le canzoni a cui l'utente ha messo 'Mi piace' nella libreria

#A questa pagina ha accesso chiunque
#Semplicemente vengono collezionate le canzoni a cui l'utente ha messo 'Mi piace' e in una lista
#vengono inserite n-uple contenenti le informazioni da visualizzare come il nome, la durata, gli album che la contengono, ecc..
#Cliccando sull'icona o sul nome si viene reindirizzati alla pagina della canzone
#Cliccando sul nome dell'artista si viene reindirizzati alla pagina dell'artista
#In cima alla pagina dei bottoni permettono di scorrere la libreria e passare ad altri contenuti
 
@library_bp.route('/songs')
@login_required
def songs():
    if(current_user.Profile == 'Artist'):
        session = Session(bind=engine["artist"])
    elif(current_user.Profile == 'Premium'):
        session = Session(bind=engine["premium"])
    else:
        session = Session(bind=engine["free"])
        
    playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
    songs = session.query(Songs).filter(Songs.Id.in_(session.query(Users_liked_Songs.song_id).filter(Users_liked_Songs.user_email==current_user.Email)))
    songs_id = session.query(Songs.Id).filter(Songs.Id.in_(session.query(Users_liked_Songs.song_id).filter(Users_liked_Songs.user_email==current_user.Email)))
    #albums = session.query(Albums).filter(Albums.Id.in_(session.query(AlbumsSongs.album_id).filter(AlbumsSongs.song_id.in_(session.query(Songs.Id).filter(Songs.Id.in_(songs_id)))))).all()
    
    lst_s=[]
    for s in songs:
        albums = session.query(Albums).filter(Albums.Id.in_(session.query(AlbumsSongs.album_id).filter(AlbumsSongs.song_id==s.Id))).all()
        artist = session.query(Users).filter(Users.Email == s.Artist).first()
        lst_s.append([s.Name, artist.Name, s.Genre, s.Duration, s.Id, artist.Email, albums])
    
    return render_template("songs.html", playlists=playlists, user=current_user, songs=lst_s)

blueprints/lib/templates/album.html
{% extends 'layout.html' %}

<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #2b2a2a;
    }
    
    li {
        float: left;
    }
    
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 1vw 1.2vw;
        text-decoration: none;
    }
    
    li a:hover{
        border-radius: 10vw;
        background-color: #1ed760;
    }
</style>

{% block content %}
<ul>
    <li><a href="{{url_for('library_bp.library',user=user,playlists=playlists)}}">Playlist</a></li>
    <li style="border-radius: 10vw; background-color: #1ed760;">Album</li>
    <li><a href="{{url_for('library_bp.artists',user=user,playlists=playlists)}}">Artists</a></li>
    <li><a href="{{url_for('library_bp.songs',user=user,playlists=playlists)}}">Songs</a></li>
</ul>

<dl>
    {% for a in albums %}
    <dt style="display:inline;"> 
        <a href="{{url_for('album_bp.album',user=user,playlists=playlists,album=a)}}">
            <figure style="display:inline-block; width:20%;">
                <img src="..\static\img\gallery.png" style="width:100%;">
                <figcaption style="text-align:center;"> {{a.Name}} </figcaption>
            </figure>  
        </a> 
    </dt>
    {% endfor %}
</dl>
{% endblock %}

blueprints/lib/templates/albums.html
{% extends 'layout.html' %}

{% block content %}
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #2b2a2a;
    }
    
    li {
        float: left;
    }
    
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 1vw 1.2vw;
        text-decoration: none;
    }
    
    li a:hover{
        border-radius: 10vw;
        background-color: #1ed760;
    }
</style>


<ul>
    <li><a href="{{url_for('library_bp.library')}}">Playlist</a></li>
    <li style="border-radius: 10vw; background-color: #1ed760;"><a>Albums</a></li>
    <li><a href="{{url_for('library_bp.songs')}}">Songs</a></li>
</ul>

<dl>
    <table style="width:98%; padding-left:2%;"> 
        <tr style="border-bottom: 0.20vw solid rgb(219, 219, 213);">
            <th style="width:20%; text-align:left;"> TITOLO </th>
            <th style="width:20%; text-align: center;"> ARTISTA </th>
            <th style="width:20%; text-align: center;"> CASA DISCOGRAFICA </th>
            <th style="width:20%; text-align: center;"> DATA </th>
            <th style="width:20%; text-align: right;"> DURATA </th>
        </tr>
        {% for a in albums %}
        <tr>
            <td> <a href="{{url_for('album_bp.show_album', album_id = a[5], artist=a[6])}}"><img src="static\img\gallery.png" style="width:10% ;">{{a[0]}}</a>  </td>
            <td style="text-align:center;"> <a href="{{url_for('artist_bp.show_artist', artist_email=a[6])}}">{{a[1]}} </a> </td>
            <td style="text-align:center;"> {{a[2]}} </td>
            <td style="text-align:center;"> {{a[3]}} </td>
            <td style="text-align:right;"> {{a[4]}} </td>
            
        </tr>
        {% endfor %}
    </table>
</dl>
{% endblock %}

blueprints/lib/templates/library.html
{% extends 'layout.html' %}

{% block content %}
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #2b2a2a;
    }
    
    li {
        float: left;
    }
    
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 1vw 1.2vw;
        text-decoration: none;
    }
    
    li a:hover{
        border-radius: 10vw;
        background-color: #1ed760;
    }
</style>

<ul>
    <li style="border-radius: 10vw; background-color: #1ed760;"><a>Playlist</a></li>
    <li><a href="{{url_for('library_bp.albums')}}">Album</a></li>
    <li><a href="{{url_for('library_bp.songs')}}">Songs</a></li>
</ul>

<dl>
    {% for p in playlists %}
    <dt style="display:inline;"> 
        <a href="{{url_for('playlist_bp.show_playlist_content',playlist_id=p.Id)}}">
            <figure style="display:inline-block; width:20%;">
                <img src="..\static\img\gallery.png" style="width:100%;">
                <figcaption style="text-align:center;"> {{p.Name}} </figcaption>
                <figcaption style="text-align:center;">
                    <a href="{{url_for('playlist_bp.delete_playlist',pl_id=p.Id)}}">
                        <img src="static\img\cancel.png" style="width:30%;">
                    </a>
                    <a href="{{url_for('playlist_bp.edit_playlist',pl_id=p.Id)}}">
                        <img src="static\img\edit.png" style="width:30%;">
                    </a> 
                </figcaption>  
            </figure>
            
        </a>
    </dt>
    {% endfor %}
</dl>
{% endblock %}

blueprints/lib/templates/songs.html
{% extends 'layout.html' %}

{% block content %}
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #2b2a2a;
    }
    
    li {
        float: left;
    }
    
    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 1vw 1.2vw;
        text-decoration: none;
    }
    
    li a:hover{
        border-radius: 10vw;
        background-color: #1ed760;
    }
</style>

<ul>
    <li><a href="{{url_for('library_bp.library')}}">Playlist</a></li>
    <li><a href="{{url_for('library_bp.albums')}}">Album</a></li>
    <li style="border-radius: 10vw; background-color: #1ed760;"><a>Songs</a></li>
</ul>

<dl>
    <table style="width:98%; padding-left:2%;"> 
        <tr style="border-bottom: 0.20vw solid rgb(219, 219, 213);">
            <th style="width:20%; text-align:left;"> TITOLO </th>
            <th style="width:20%; text-align: center;"> ARTISTA </th>
            <th style="width:20%; text-align: center;"> GENERE </th>
            <th style="width:20%; text-align: center;"> ALBUM </th>
            <th style="width:20%; text-align:right;"> DURATA </th>
        </tr>
        {% for s in songs %}
        <tr>
            
            <td> <a href="{{url_for('song_bp.show_song', song_id = s[4])}}"><img src="static\img\gallery.png" style="width:10% ;">{{s[0]}}</a> </td>
            <td style="text-align:center;"><a href="{{url_for('artist_bp.show_artist', artist_email=s[5])}}">{{s[1]}}</a></td>
            <td style="text-align:center;"> {{s[2]}} </td>
            <td style="text-align:center;"> 
                {% for a in s[6] %}
                <a href="{{url_for('album_bp.show_album', album_id = a.Id, artist=s[5])}}"> - {{a.Name}}  </a>    
                {% endfor %}
            </td>
            <td style="text-align:right;"> {{s[3]}} </td>
            
        </tr>
        {% endfor %}
    </table>
</dl>
{% endblock %}