blueprints/song/routes.py
from re import template
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import *
from blueprints.models import *
import datetime
from ..forms import upload_SongForm
from sqlescapy import sqlescape
from sqlalchemy import exc

# Blueprint Configuration
song_bp = Blueprint(
    'song_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


#Route per caricare una canzone sull'applicazione

#Solo gli artisti possono creare contenuti. Se un utente Free o Premium dovesse in qualche modo accedere a questa 
#funzionalità, verrebbe rimandato alla home. 
#Nel blocco try..except.., nel blocco try, vengono caricate le informazioni necessarie al caricamento della canzone,
#prese dall'apposito form
#Se tutte le informazioni sono ammesse, viene creata la canzone, caricata sul DB, associato all'artista che l'ha creata e 
#l'utente viene reindirizzato alla pagina contente le sue canzoni
#Se le informazioni non sono ammesse, e questo avviene quando 1)il nome della canzone eccede i 10 ch (gestito dal form)
#                                                             2)il nome della canzone è uguale a quello di una canzone 
#                                                               già esistente e caricata dal medesimo artista (gestito dal blocco except)
#si resterà sulla pagina dedicata al form, che mostrerà specifici messaggi d'errore


@song_bp.route('/upload_song', methods=['GET', 'POST'])
@login_required # richiede autenticazione
def upload_song():
    if(current_user.Profile != 'Artist'):
        return redirect(url_for("home_bp.home"))
    else:
        session = Session(bind=engine["artist"])

    try:
        playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
        form = upload_SongForm()
        
        if form.validate_on_submit():
            name = sqlescape(form.name.data)
            time = form.time.data
            genre = form.genre.data
            if form.type.data == 'Premium':
                restriction = True
            else:
                restriction = False  
            song = Songs(name, time, genre, restriction, current_user.Email)
            artist = session.query(Artists).filter(Artists.Email == current_user.Email).first()
            Songs.create_song(song, session)
            Artists.add_song_if_artist(artist, song, session)
                
            return redirect(url_for("song_bp.show_my_songs", user=current_user, playlists=playlists))    
        return render_template('upload_song.html',form=form, user=current_user, playlists=playlists)

    except exc.SQLAlchemyError as err:
        session.rollback()
        flash(err.orig.diag.message_primary, 'error') 
        return render_template('upload_song.html',form=form, user=current_user, playlists=playlists)
    

#Route per modificare una canzone

#Se un utente Free o Premium dovesse in qualche modo accedere a questa funzionalità, verrebbe rimandato alla home.
#Lo stesso avviene se un artista dovesse accedere a questa funzionalità per una canzone non sua.
#Nel blocco try..except.., nel blocco try, vengono caricate le informazioni necessarie alla modifica della canzone,
#prese dall'apposito form
#Se tutte le informazioni sono ammesse, viene modificata la canzone.
#Da notare che, nel caso in cui la canzone fosse originariamente un contenuto Free che tramite modifica viene
#alzato a contenuto Premium, da eventuali album Free che la contengono la canzone viene rimossa, e le durate di
#ciascuno si aggiornano di conseguenza
#Se le informazioni non sono ammesse, e questo avviene quando 1)il nome della canzone eccede i 10 ch (gestito dal form)
#                                                             2)il nome della canzone è uguale a quello di una canzone 
#                                                               già esistente e caricata dal medesimo artista (gestito dal blocco except)
#si resterà sulla pagina dedicata al form, che mostrerà specifici messaggi d'errore


@song_bp.route('/edit_song/<song_id>', methods=['GET', 'POST'])
@login_required # richiede autenticazione
def edit_song(song_id):
    if(current_user.Profile != 'Artist'):
        return redirect(url_for("home_bp.home"))
    else:
        session = Session(bind=engine["artist"]) 
        
    try:
        playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
        song = session.query(Songs).filter(Songs.Id == song_id).first()
        if(song.Artist != current_user.Email):
            return redirect(url_for("home_bp.home"))
           
        if song.Is_Restricted == True:
            restriction = 'Premium'
        else:
            restriction = 'Free'
        
        form = upload_SongForm(name=song.Name, time=song.Duration, genre=song.Genre, type = restriction)
        
        if form.validate_on_submit():
            name = sqlescape(form.name.data)
            time = form.time.data
            genre = form.genre.data
            if form.type.data == 'Premium':
                restriction = True
            else:
                restriction = False  
            
            if(song.Is_Restricted == False and restriction):
                albums = session.query(Albums).filter(Albums.Id.in_(session.query(AlbumsSongs.album_id).filter(AlbumsSongs.song_id==song_id)), Albums.Is_Restricted==False)
                st = song.Duration
                date = datetime.date(10, 10, 10)
                for a in albums:
                    at = a.Duration
                    start = datetime.datetime.combine(date, at)
                    minus = datetime.timedelta(seconds=st.second, minutes=st.minute, hours=st.hour)
                    end = start - minus

                    Albums.remove_song(a, song_id, session)

                    Albums.update_album(a.Id, a.Name, a.ReleaseDate, a.Record_House, end.time(), a.Is_Restricted, session)

            Songs.update_song(song_id, name, time, genre, restriction, session)
                
            return redirect(url_for("song_bp.show_my_songs", user=current_user, playlists=playlists)) 
            
        return render_template("edit_song.html", user=current_user, playlists=playlists, id=song_id, form=form)

    except exc.SQLAlchemyError as err:
        session.rollback()
        flash(err.orig.diag.message_primary, 'error') 
        return render_template("edit_song.html", user=current_user, playlists=playlists, id=song_id, form=form)
            


#Route per eliminare una canzone

#Se un utente Free o Premium dovesse in qualche modo accedere a questa funzionalità, verrebbe rimandato alla home.
#Lo stesso avviene se un artista dovesse accedere a questa funzionalità per una canzone non sua.
#Innanzitutto, se una canzone viene eliminata, le playlist e gli album che la contengono vanno aggiornati di conseguenza.
#Le loro durate vengono quindi aggiornate sottraendo il tempo della canzone
#Viene poi chiamata l'opportuna funzione in Songs

@song_bp.route('/delete_song/<song_id>', methods=['GET', 'POST'])
@login_required # richiede autenticazione
def delete_song(song_id):
    if(current_user.Profile != 'Artist'):
        return redirect(url_for("home_bp.home"))
    else:
        session = Session(bind=engine["artist"]) 

    albums = session.query(Albums).filter(Albums.Id.in_(session.query(AlbumsSongs.album_id).filter(AlbumsSongs.song_id==song_id)))
    playlists = session.query(Playlists).filter(Playlists.Id.in_(session.query(PlaylistsSongs.playlist_id).filter(PlaylistsSongs.song_id==song_id)))
    song=session.query(Songs).filter(Songs.Id == song_id).first()

    if(song.Artist != current_user.Email):
        return redirect(url_for("home_bp.home"))
            
    st = song.Duration
    minus = datetime.timedelta(seconds=st.second, minutes=st.minute, hours=st.hour)
    date = datetime.date(10, 10, 10)
        
    for a in albums:
        start=datetime.datetime.combine(date, a.Duration)
        end = start - minus
        Albums.update_album(a.Id, a.Name, a.ReleaseDate, a.Record_House, end.time(), a.Is_Restricted, session)

    for p in playlists:
        start=datetime.datetime.combine(date, p.Duration)
        end = start - minus
        Playlists.update_playlist(p.Id, p.Name, end.time(), session)

    Songs.delete_song(song_id, session)
    return redirect(url_for("song_bp.show_my_songs"))

#Route per raccogliere e mostrare tutti le canzoni di un artista

#Se un utente Free o Premium dovesse in qualche modo accedere a questa funzionalità, verrebbe rimandato alla home.
#Tramite due query vengono collezionate le canzoni pubbliche e le canzoni premium dell'artista che accede alla pagina
#Nella pagina verrano visualizzate adeguatamente separate nelle due categorie
#Oltre all'icona e al nome della canzone, vengono visualizzati anche un bottone per eliminare e uno per modificare la canzone
#In cima alla pagina un bottone da la possibilità di creare nuovi album

@song_bp.route('/show_my_songs')
@login_required # richiede autenticazione
def show_my_songs():
    if(current_user.Profile != 'Artist'):
        return redirect(url_for("home_bp.home"))
    else:
        session = Session(bind=engine["artist"]) 

    songs_free = session.query(Songs).filter(Songs.Artist == current_user.Email, Songs.Is_Restricted == False)
    songs_premium = session.query(Songs).filter(Songs.Artist == current_user.Email, Songs.Is_Restricted == True)
    playlists = session.query(Playlists).filter(Playlists.User == current_user.Email)
    
    return render_template("show_my_songs.html", songs_free = songs_free, songs_premium = songs_premium, user = current_user, playlists = playlists)



#Route per mettere 'Mi piace' ad una canzone

#A questa funzionalità ha accesso chiunque
#Prima di effettuare l'azione e modificare il numero di 'Mi piace' della canzone, è opportuno controllare che
#l'utente in questione non abbia già messo 'Mi piace' alla canzone, in modo che utenti malintenzionati

blueprints/song/templates/edit_song.html
{% extends 'layout.html' %}

{% block content %}
<style>
  fieldset{
    border: 0;
    background-color: #212221;
    border-radius: 4vw;
    text-align: center; 
    width: 60%;
    margin: auto;
  }
  ul{
    list-style-type: none;
  }
  form{
    text-align: center;
  }
  .submit_btn {
    background-color:#1ed760; 
    border:none; 
    border-radius:10vw;
    color: rgb(249, 248, 241);
    padding: 0.8vw 1.2vw;
  }
  .submit_btn:hover {
    background-color: #16a748;
  }
</style>

<h1> Aggiorna le informazioni del tuo brano </h1> 

{% with errors = get_flashed_messages(category_filter=["error"]) %}
  {% if errors %}
    <div id="myErrors" class="alert-message block-message error" style="text-align: center; background-color: #1d1d1d; border-radius: 5vw;">
          <ul>
              {%- for msg in errors %}
                <li style="text-align: center;">{{ msg }}</li>
              {% endfor -%}
          </ul>
          <a id="closeButton" class="submit_btn" href="#" onclick="myFunction()" style="text-align: center; padding: 0 0.8vw;">Ok</a>
    </div>
  {% endif %}
{% endwith %}

<script>
  function myFunction() {
    var x = document.getElementById("myErrors");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>

<table>
  <tr>
    <td style="vertical-align:top; width:40%;">
      <img src="..\static\img\gallery.png" style="width:100%;">
    </td>
    <td style="width:60%;">
      <form method="POST" action="{{ url_for('song_bp.edit_song', song_id=id) }}">
        {{ form.csrf_token }}
    
        <fieldset class="form-field" >
          {{ form.name.label }} 
          {{ form.name }}
          {% if form.name.errors %}
            <ul class="errors">
              {% for error in form.name.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message"> {{error}} </span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        <fieldset class="form-field">
          {{ form.time.label }} 
          {{ form.time }}
          {% if form.time.errors %}
            <ul class="errors">
              {% for error in form.time.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        <fieldset class="form-field">
          {{ form.genre.label }} 
          {{ form.genre }}
          {% if form.genre.errors %}
            <ul class="errors">
              {% for error in form.genre.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        <fieldset class="form-field">
          {{ form.type.label }} 
          {{ form.type }}
          <i class="fas fa-caret-down"></i>
          {% if form.type.errors %}
            <ul class="errors">
              {% for error in form.type.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        {{ form.submit(class_="submit_btn") }}
      </form>
    </td>
  </tr>
</table>
{% endblock %}

blueprints/song/templates/show_my_songs.html
{% extends 'layout.html' %}

{% block content %}
   
    <div class="w3-container"> <h1>Le tue canzoni <a href="{{ url_for('song_bp.upload_song') }}"> <img src="..\static\img\add.png", style="width:5% ;transform: translateY(-25%)"> </a></h1> </div>
    <dl>
        <h1 style="text-align: center;">Brani pubblici</h1>
        {% for s in songs_free %}
            <dt style="display:inline;"> 
                <figure style="display:inline-block; width:15%;">
                    <img src="static\img\gallery.png" style="width:100%;">
                    <figcaption style="text-align:center;">
                       <a href="{{ url_for('song_bp.show_song', song_id=s.Id) }}" >{{s.Name}}</a>
                    </figcaption>
                    <figcaption style="text-align:center;">
                        <a href="{{url_for('song_bp.delete_song',song_id=s.Id)}}">
                            <img src="static\img\cancel.png" style="width:30%;">
                        </a>
                        <a href="{{url_for('song_bp.edit_song',song_id=s.Id)}}">
                            <img src="static\img\edit.png" style="width:30%;">
                        </a> 
                    </figcaption>
                </figure>
            </dt>
        {% endfor %}
    </dl>

    <hr style="height:0.3vw;border-width:0; background-color: white;">

    <dl>
        <h1 style="text-align: center;">Brani premium</h1>
        {% for s in songs_premium %}
            <dt style="display:inline;"> 
                <figure style="display:inline-block; width:15%;">
                    <img src="static\img\gallery.png" style="width:100%;">
                    <figcaption style="text-align:center;">
                        <a href="{{ url_for('song_bp.show_song', song_id=s.Id) }}" >{{s.Name}}</a> 
                    </figcaption>
                    <figcaption style="text-align:center;">
                        <a href="{{url_for('song_bp.delete_song',song_id=s.Id)}}">
                            <img src="static\img\cancel.png" style="width:30%;">
                        </a>
                        <a href="{{url_for('song_bp.edit_song',song_id=s.Id)}}">
                            <img src="static\img\edit.png" style="width:30%;">
                        </a> 
                    </figcaption>
                </figure>
            </dt>
        {% endfor %}
    </dl>

{% endblock %}

blueprints/song/templates/show_song.html
{% extends 'layout.html' %}

{% block content %}

<table>
    <tr>
        <td style="width:32%;">
            <img src="..\..\static\img\gallery.png" style="width:100%;">
        </td>
        <td>
            <h1>{{song.Name}}</h1>
            <p>
              <a href="{{url_for('artist_bp.show_artist', artist_email=song.Artist)}}">{{artist_name}}</a> - {{song.Duration}} - {{song.Genre}} - {{song.N_Likes}} like
            </p>
            {%if song.Artist != user.Email%}
                {% if like == False %}
                    <a href="{{url_for('song_bp.add_to_liked_songs',song_id=song.Id, page=2)}}">
                        <img src="..\..\static\img\like.png" style="width:10%;">
                    </a>
                {% else %}
                    <a href="{{url_for('song_bp.remove_from_liked_songs',song_id=song.Id, page=2)}}">
                        <img src="..\..\static\img\dislike.png" style="width:10%;">
                    </a>
                {% endif %}
            {% endif %}
        </td>
    </tr>
</table>

{% endblock %}

    

blueprints/song/templates/upload_song.html
{% extends 'layout.html' %}

{% block content %}
<style>
  fieldset{
    border: 0;
    background-color: #212221;
    border-radius: 4vw;
    text-align: center; 
    width: 60%;
    margin: auto;
  }
  ul{
    list-style-type: none;
  }
  form{
    text-align: center;
  }
  .submit_btn {
    background-color:#1ed760; 
    border:none; 
    border-radius:10vw;
    color: rgb(249, 248, 241);
    padding: 0.8vw 1.2vw;
  }
  .submit_btn:hover {
    background-color: #16a748;
  }
</style>

<h1> Condividi il tuo brano con il mondo </h1> 

{% with errors = get_flashed_messages(category_filter=["error"]) %}
  {% if errors %}
    <div id="myErrors" class="alert-message block-message error" style="text-align: center; background-color: #1d1d1d; border-radius: 5vw;">
          <ul>
              {%- for msg in errors %}
                <li style="text-align: center;">{{ msg }}</li>
              {% endfor -%}
          </ul>
          <a id="closeButton" class="submit_btn" href="#" onclick="myFunction()" style="text-align: center; padding: 0 0.8vw;">Ok</a>
    </div>
  {% endif %}
{% endwith %}

<script>
  function myFunction() {
    var x = document.getElementById("myErrors");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>

<table>
  <tr>
    <td style="vertical-align:top; width:40%;">
      <img src="..\static\img\gallery.png" style="width:100%;">
    </td>
    <td style="width:60%;">
      <form method="POST" action="{{ url_for('song_bp.upload_song') }}">
        {{ form.csrf_token }}
    
        <fieldset class="form-field" >
          {{ form.name.label }} 
          {{ form.name }}
          {% if form.name.errors %}
            <ul class="errors">
              {% for error in form.name.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message"> {{error}} </span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        <fieldset class="form-field">
          {{ form.time.label }} 
          {{ form.time }}
          {% if form.time.errors %}
            <ul class="errors">
              {% for error in form.time.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        <fieldset class="form-field">
          {{ form.genre.label }} 
          {{ form.genre }}
          {% if form.genre.errors %}
            <ul class="errors">
              {% for error in form.genre.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        <fieldset class="form-field">
          {{ form.type.label }} 
          {{ form.type }}
          <i class="fas fa-caret-down"></i>
          {% if form.type.errors %}
            <ul class="errors">
              {% for error in form.type.errors %}
                <li class="error">
                  <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </fieldset>
        <br>
        {{ form.submit(class_="submit_btn") }}
      </form>
    </td>
  </tr>
</table>
{% endblock %}